services:
  unfisk:
    build:
      context: .
    image: trellisfw/unfisk
    restart: unless-stopped
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED
      - NODE_ENV=${NODE_ENV:-development}
      - DEBUG=${DEBUG-*:error,*:warn,*:info}
      - token=${UNFISK_TOKEN}
      # Connect to host if DOMAIN not set?
      # You should really not rely on this though. Set DOMAIN.
      - domain=${DOMAIN:-host.docker.internal}
